### ISSUE TITLE
UE 5.5 Support?

### ISSUE THREAD

**Issue by Mr-Foxtrot** [nicholas477/AsyncReadRT#4]
I've been using this quite a bit in my 5.3 project, this plugin is great for tracking color of drawn bloodsplatters to change footprint colors to match! However recently i've been attempting to move my project to 5.5 in hopes to utilize some of it's newest features.

I've tried recompiling it myself but i'm getting a large list of errors:

...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(17): error C2061: syntax error: identifier 'EPixelFormat'
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(19): error C2065: 'Format': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(20): error C2050: switch expression not integral
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(21): error C2653: 'EPixelFormat': is not a class or namespace name
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(21): error C2065: 'PF_FloatRGBA': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(21): error C2131: expression did not evaluate to a constant
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(21): note: a non-constant (sub-)expression was encountered
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(24): error C2065: 'OutColor': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(25): error C2065: 'OutColor': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(26): error C2065: 'OutColor': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(27): error C2065: 'OutColor': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(30): error C2653: 'EPixelFormat': is not a class or namespace name
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(30): error C2065: 'PF_B8G8R8A8': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(30): error C2131: expression did not evaluate to a constant
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(30): note: a non-constant (sub-)expression was encountered
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(33): error C2065: 'OutColor': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(34): error C2065: 'OutColor': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(35): error C2065: 'OutColor': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(36): error C2065: 'OutColor': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(37): error C2065: 'OutColor': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(41): error C2065: 'Format': undeclared identifier
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(41): error C3553: decltype expects an expression not a type
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(41): error C2062: type 'unknown-type' unexpected
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(41): error C2653: 'UE_FMT_STR_Checker': is not a class or namespace name
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(41): error C3861: 'Check': identifier not found
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(41): error C2131: expression did not evaluate to a constant
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(41): note: failure was caused by a read of an uninitialized symbol
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(41): note: see usage of 'UE::Core::Private::FormatStringSan::FResult::Status'
...Plugins\AsyncReadRT\Source\AsyncReadRT\Public\AsyncReadRT.h(41): fatal error C1903: unable to recover from previous error(s); stopping compilation

Could this be updated to support 5.5? I currently don't have any alternative solutions to work without it, I'd greatly appreciate it if you could update this.

**Comment by nicholas477** [comment]
I pushed a commit that worked for me for 5.5, try it out

**Comment by Mr-Foxtrot** [comment]
Just recompiled it, still got exactly the same errors but this time it just outputted all the plugin files anyway and seemingly works?
Colors seem to read fine, i'm going to test a shipping build to make sure nothing breaks there.

**Comment by nicholas477** [comment]
🤔🤔🤔🤔 are you compiling for windows, linux, mac, or android?

**Comment by Mr-Foxtrot** [comment]
> 🤔🤔🤔🤔 are you compiling for windows, linux, mac, or android?

Windows only

**Comment by nicholas477** [comment]
hey wait are these compiler errors or intellisense errors?

**Comment by Mr-Foxtrot** [comment]
definitely not intellisense, I see what was going wrong: apologies for the confusion

I tried initially just dropping in the plugin into the project plugins folder like usual, but for some reason it failed to recompile, so I then opted to use RunUAT.bat in the engine folder to recomp the plugin myself to work in 5.5, and that produced errors.

However, I just tried dropping it back into the plugins folder again, and it worked fine without any problems, my guess is my browser cached the previous version from before the update or something: all is good now!

**Comment by nicholas477** [comment]
You silly devil 👺

**Comment by Mr-Foxtrot** [comment]
oh and of course:
Thank you!
